// data.js — content + palette constants for the Reel portfolio

// Palettes: [bg, surface, ink, accent, muted]
export const PALETTES = [
  ["#0e0c0a", "#1a1714", "#f0eae0", "#ff6a3d", "#7a7068"], // warm dark + amber
  ["#0a0e10", "#16191c", "#e8ecf0", "#5ec2ff", "#7d8590"], // arctic + cyan
  ["#0c0a14", "#16131e", "#ece6f4", "#c099ff", "#7d7585"], // plum + lilac
  ["#0a0a0a", "#141414", "#ededed", "#ff3e58", "#7c7c7c"], // black + signal red
];

// Default theme — black + signal red.
export const DEFAULT_PALETTE = PALETTES[3];

export const GRAIN_URL =
  "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 240 240' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\")";

export const PROJECTS = [
  {
    idx: 1,
    year: "2024—NOW",
    kind: "product · founding",
    title: "bello.art",
    role: "Founder + CEO",
    blurb:
      "A visual operating system for online sellers — the layer between product creation and online distribution. Selling online today means stitching together Photoshop, Canva, AI tools, cloud folders and a dozen upload flows. bello replaces that. The first surface — high-end interior mockups for independent artists — has sold 10K+.",
    details: [
      "bello.art is the layer that sits between product creation and online distribution. Selling online today demands an entire visual identity — listing images, lifestyle photos, mockups, videos, thumbnails, branding assets, sizing diagrams, packaging visuals, and platform-specific content for marketplaces and social media.",
      "Most creators stitch this together from a fragmented stack: Photoshop, Canva, AI generators, cloud folders, and manual uploads across Etsy, Instagram, Pinterest, TikTok, and Shopify. bello replaces that workflow with a single visual studio purpose-built for sellers.",
      "We launched the first surface in 2024 — high-end interior mockups for independent artists. The studio elevates an artist's work while helping their customers visualize how a piece would fit in their own home. Over 10,000 mockups sold to date. The Studio, Packs, Feeds, Sizing, and AI Imaging surfaces are next.",
    ],
    tags: ["product", "ai imaging", "ecommerce"],
    colors: ["#3a1810", "#ff8a4a", "#ffd09c", "#d96030"],
    seed: 3,
    media: "/bello-home.jpg",
    link: "https://bello.art",
  },
  {
    idx: 2,
    year: "2022—2024",
    kind: "partnership · creator",
    title: "Adobe Photoshop Partner",
    role: "Sponsored Creator",
    blurb:
      "Two years as an Adobe-sponsored Photoshop creator — making art for Photoshop's worldwide community, 60M+ views across their social channels. The chapter where I left big tech for a public craft, learned how attention actually moves online, and met the artists whose problem became bello.art.",
    details: [
      "After seven years at Meta, I wanted to take a break from big tech.",
      "I had spent years working with data, experiments, metrics, and product strategy. I loved parts of that work, but it also used a very specific part of my brain. I wanted to do something more creative, more visual, and more public. I also wanted to understand marketing, branding, and distribution more deeply — not as abstract business concepts, but as skills I could practice directly.",
      "The internet had changed. We were living in the attention economy, where the best product does not always win. The product people notice, understand, remember, and share often does. In that world, marketing is not a layer you add at the end. In many ways, marketing is part of the product.",
      "So I decided to create something online.",
      "I had always loved Photoshop, and I wanted to spend my post-Meta break making digital art. That became [Fauna Fables](https://instagram.com/faunafables), a Photoshop art account where I created surreal animal scenes: wallabies catapulting armadillos at a castle, frogs causing trouble, birds in dramatic situations, animals doing legendary or ridiculous things. The work was playful, visual, and story-driven. I would also document the process so people could learn from it, not just watch the finished piece appear.",
      "I started posting on Instagram and TikTok. Over time, the videos began to find an audience. Eventually, they found Photoshop's official TikTok account.",
      "Adobe reached out about a sponsorship, and that became the start of a two-year collaboration with the Photoshop team. I created content for their social channels across Instagram, TikTok, YouTube, Facebook, and Twitter, working closely with Edelman, Adobe's PR firm, and the Photoshop marketing team.",
      "Over that period, I created 23 short-form videos and 3 original artworks for Adobe. The content generated 60M+ views and 1M+ likes, and I became one of the top-performing creators on Photoshop's channels by view count. For a while, I was also one of only a few hundred accounts followed by Photoshop on Instagram, which had more than 6 million followers at the time.",
      "Going from Photoshop hobbyist to sponsored Photoshop creator was surreal.",
      "The work generally fell into three formats. Some videos were speed edits, showing the rapid progression of an artwork in a fun, satisfying way. Others were tutorials, where I walked through a specific technique or visual effect. And some were pure entertainment, like showing how to shave a llama in Photoshop.",
      "It was fun, but it was not easy. I had to pitch ideas, prototype them, get approval, create the artwork, edit the video, incorporate feedback, and deliver everything on tight timelines. Because the content was going out on Photoshop's official channels, the bar was high. The work needed to be visually impressive, technically useful, brand-safe, entertaining, and native to the platforms where it would appear.",
      "That experience taught me a lot about creative distribution. A good piece of content is not just a good idea. It needs a strong hook, a clear visual payoff, a reason to keep watching, and a format that feels natural in the feed. It also taught me how different it is to create for an audience, not just for yourself.",
      "I also briefly tried turning Fauna Fables into a home decor brand. Over a few months, I designed plates, pillows, stools, glasses, and other objects using the animal artwork, and presented the collection at Maison&Objet in Paris. The brand did not ultimately take off, but it was a valuable crash course in manufacturing, merchandising, and the home decor market.",
      "More importantly, it sharpened my interest in how artists package and present their work commercially. During that period, I met a lot of artists and started noticing a business problem that interested me even more than the Photoshop work itself: many artists were trying to sell online, but struggled to create the visual assets they needed — mockups, product images, shop visuals, and social content that made their art feel premium.",
      "That problem became the seed for my next adventure: [bello.art](https://bello.art), a visual commerce platform helping artists create premium product imagery for selling online. The Photoshop work taught me how artists create, market, and distribute visual work. The home decor experiment taught me how hard it is to turn creative work into sellable products. Together, they pointed me toward the product I wanted to build next: tools that help artists present their work beautifully and commercially.",
    ],
    tags: ["adobe", "photoshop", "creator", "partnership"],
    colors: ["#0d1217", "#31a8ff", "#a8dcff", "#1d4870"],
    seed: 23,
    media: "/adobe-photoshop.jpg",
  },
  {
    idx: 3,
    year: "2020—2021",
    kind: "leadership · data",
    title: "AR Experiences @ Meta",
    role: "Data Science Manager",
    blurb:
      "Two years leading data science for AR Experiences in Meta's Reality Labs — a ~100-person org building mobile AR for the future computing platform that would one day become AR glasses.",
    details: [
      "In 2020, I moved into Meta's Reality Labs to lead data science for AR (Augmented Reality) Experiences, a pillar of roughly 100 people working on the mobile experiences that would inform Meta's long-term AR glasses strategy.",
      "We were operating in a strange space: building for a future computing platform before the hardware was ready, using today's phones as the proving ground. The work spanned commerce, world effects, location-based experiences, remote presence, creator tools, and early explorations around 3D objects and future AR surfaces. I managed a team of five data scientists supporting that broader product organization.",
      "As an IC, my job had been to find product levers myself: measure the system, identify opportunities, run experiments, and help teams ship better products. As a manager, my job was to build a data function that could do that across a much larger surface area. I had to help my team turn messy signals into clear recommendations, then make sure those recommendations reached the leaders and partner teams who could act on them.",
      "In a large company, good analysis does not automatically create impact. A data scientist can do excellent work and still have it disappear into a doc, get trapped inside one team, or fail to reach the people who can act on it. One of the most important parts of my role was helping the right insights survive the organization.",
      { h: "Solving the AR creator bottleneck" },
      "One of the clearest examples came from our work on the AR creator ecosystem.",
      "When I arrived in Reality Labs, our flagship creator product was Spark AR. Spark let creators build AR effects and publish them directly to Instagram Stories and Facebook Stories. It was powerful, but it was also complex. Creators had to learn the tool, understand what was possible, find inspiration, build the effect, and then get it approved and distributed.",
      "That was a lot of friction for a still-small creator base.",
      "When my team and I looked more closely at what people were actually publishing, we found something important: most Spark content was not deeply interactive AR. It was often just 3D content — a static object, an animated object, or something relatively simple. The platform was capable of much more, but the actual supply being created was telling us something different.",
      "That insight changed how we thought about the ecosystem. If most creators were using a complex AR tool to publish relatively simple 3D objects, maybe the answer was not to keep pushing everyone through Spark. Maybe we needed a simpler path: upload a 3D object directly online, and let the system do the work behind the scenes to make it available as an AR effect.",
      "Spark could still exist for advanced creators and more sophisticated effects. But if the goal was to grow 3D inventory for future AR surfaces, we needed a lower-friction supply engine.",
      "That work helped lead to a new product direction and a dedicated effort to build a simpler 3D content platform. Compared with our Spark baseline, the first version increased AR content inventory by 40×.",
      { h: "Finding distribution for 3D content" },
      "But increasing 3D inventory was only half the problem. Creators also need distribution.",
      "Why would someone spend time making 3D content if nobody was likely to see it? If content only lived inside a Story, it could disappear quickly or remain trapped inside a surface where discovery was limited. Around the same time, NFTs and digital collectibles were becoming culturally relevant, and it was plausible that immersive 3D objects could become a new kind of content on Facebook and Instagram.",
      "I performed an opportunity analysis around bringing 3D posts into Feed. The question was not simply whether 3D objects were interesting. It was whether there was a path from existing behavior — posting, collecting, sharing, discovering — toward a new kind of media object that could give creators both a reason to make 3D content and a place to distribute it.",
      "The work was raised to leadership and led to conversations across Camera, 3D Scanning, and Instagram platform teams. We also found that Facebook had experimented with 3D in Feed before, with mixed results. That made the question more nuanced: was the idea wrong, or had the earlier version been limited by surface, timing, execution, or available content?",
      "Before we could fully answer that, the team was reorganized, and I left the company shortly after. But the project remains a good example of what it felt like to work in an emerging category. The job was not always to produce a clean yes-or-no answer. Sometimes it was to use data, product intuition, and a big strategic idea to make the next conversation sharper.",
      { h: "Managing a portfolio of AR bets" },
      "Another major part of the role was helping my team navigate cross-org ambiguity.",
      "My team's work spanned a very diverse set of AR bets. One IC worked on social remote presence: AR games, avatars, and interactive effects inside Messenger video calls that could make people feel more connected. Another worked on a more literal version of remote presence: using camera movement, parallax, segmentation, and AI-generated backgrounds to make a person feel more physically present on a 2D screen. Others worked on AR ads with Camera and Ads, a world-AR-first app, and location-based AR experiences across Facebook and Instagram map surfaces.",
      "The common thread was not a single product surface. It was ambiguity. Each effort required different partner teams, different metrics, and different definitions of success. My role was to help my ICs navigate that complexity: clarify the product question, identify shared goals, create visibility for their work, and frame each bet in terms of either growing AR usage now or learning where the future platform might go.",
      "That made the role both difficult and interesting. I had to keep track of many different bets, relationships, surfaces, and partner teams, then help my team find common language across them. In a space that ambiguous, leadership meant turning scattered efforts into a portfolio: some bets to grow usage now, some bets to unlock supply, and some bets to teach us where the future platform might go.",
      { h: "Scaling impact through others" },
      "The biggest shift for me as a manager was learning to scale impact without becoming the center of the work.",
      "Much of my day-to-day work was spent helping my ICs sharpen their thinking and distribution: reading drafts, publicly commenting on and sharing their work, pressure-testing metrics they worked on, clarifying the decision their work was meant to influence, and preparing them for leadership reviews. In many cases, my job was to make their work easier to understand and harder to ignore.",
      "That also meant getting out of the way. If one of my data scientists found the insight and shaped the recommendation, they should be the person presenting it. Even better, I should get other people out of their way — shielding them from bureaucracy, unnecessary meetings or asks, or anything else that hurt their productivity. So in short, give them air cover, create visibility, and make sure credit flowed to them properly.",
      "I learned that a manager's leverage often comes from small acts repeated consistently: asking the sharper question, creating the right forum, bringing in the right stakeholder, publicly reinforcing good work, and helping good work reach the people who can act on it.",
      { h: "Building the vehicle for impact" },
      "As an IC, my work was more direct: find a product problem, aim an analysis at it, and use the result to drive impact. As a manager, the work became less linear. I had to build the vehicle for impact: help my team sharpen their work, get it in front of the right people, and turn scattered insights into a clearer product direction.",
      "That was the main lesson for me: management is not about becoming the source of insight. It is about building the conditions for insight to travel.",
    ],
    tags: ["meta", "reality labs", "team lead", "ar"],
    colors: ["#101820", "#3a82c8", "#b8e0ff", "#1a4870"],
    seed: 5,
    media: "/meta-reality-labs.jpg",
  },
  {
    idx: 4,
    year: "2015—2021",
    kind: "product · data science",
    title: "Data Science @ Meta",
    role: "Data Scientist",
    blurb:
      "Seven years of product data science at Meta — across Facebook Lite, Messenger, Search, Business Platform, and Reality Labs. Less a résumé of what I shipped, more a record of how those years shaped the way I think about data and products.",
    details: [
      "This post is less a résumé of my time at Meta, and more a summary of how those years shaped the way I think about product data science.",
      "From 2015 to 2021, I worked as a data scientist at Meta across Facebook Lite, Messenger, Search, Business Platform, and Reality Labs. I worked alongside software engineers, designers, researchers, and product managers to launch hundreds of features and products over the years.",
      "My job as a data scientist was to drive impact using data, and I split my time between execution and strategy.",
      "On the execution side, I worked with teams to make products measurably better: define goals, instrument the product, identify the levers that mattered, turn them into engineering projects, run experiments, and decide what should launch.",
      "On the strategy side, I helped teams understand the bigger picture: how to measure product health, why important metrics were moving, whether an ecosystem was working, and where user behavior pointed to new product opportunities.",
      "So I was both in the trenches, working alongside engineers to quantifiably improve our products, while also in the command center, thinking strategically about the big picture of our products, ensuring we're not just optimizing for a local maxima.",
      { h: "The art of measurement" },
      "In Silicon Valley, we measure everything. How many buttons were pressed, how many posts were seen, etc. If we don't do that, we're flying blind.",
      "In 2019, I discovered that Facebook was undercounting visits to Pages by roughly 30%. Pages was a major product surface (1B+ MAU), and visit counts were part of how the company understood whether people and businesses were engaging with the product. Visits were also tied to other company metrics, like one of our company toplines: Monthly Active Businesses.",
      "I published my findings internally, and made the case to leadership that the problem was serious enough to justify a dedicated effort. That eventually led to a new team being spun up to overhaul event logging for the product. Once the new logging was in place, it revealed that Monthly Active Businesses had been off by 1% the whole time, which is significant (entire teams try to move that metric by 1% in an entire half).",
      "So data science is not only about analysis; it is also about building trust in the measurement system that a whole company depends on.",
      { h: "Translating insights to impact" },
      "Measurement also allows us to analyze how people use our products, which yields insights on how to improve them.",
      "During my work on Pages, I spent a lot of time looking at how people interacted with the product. Where they dropped off, what actions they took, and which parts of the experience created confusion based on a variety of metrics. That work surfaced more than ten usability issues across the product. The biggest issue was a cluttered interface that made it harder for people to do what they most often came to do: view a Page's posts.",
      "My hypothesis was that a leaner Page surface would be more useful to visitors. So I recruited a team of engineers and led them through a series of experiments to simplify the design and help users reach posts more quickly. Our changes showed big improvements in key page metrics, including a 2% lift in Page likes and a 5% lift in website clicks on business Pages. Those numbers might sound small in isolation. But at Meta scale, they represented meaningful improvements for millions of businesses.",
      { h: "Building new products with data" },
      "In most cases, data helps us improve existing products. But in many cases, it also helps us build brand new products.",
      "One of my favorite examples of this was helping build the first video search engine at Facebook.",
      "In the early Facebook days, people were the only entity on the platform, and the search product was largely a people-search product. You type in the bar, we show you people's profiles, you click the one you want, and you go straight to their profile.",
      "As the platform evolved, new entities emerged. Pages, Videos, Groups, etc. This meant our search engine had to evolve to cater to a broader range of query intents. People were now searching for videos they had seen in feed, movie clips, or anything else. My team was in charge of building the company's first video search product to meet that demand.",
      "My first task was to identify video-intent queries, i.e. the \"demand\" that we needed to satisfy with our search results. These were queries like \"lady gaga poker face\" or \"real madrid vs atletico\", and I used a mixture of NLP and creative entry point work to identify them. We used these queries as the basis for how we indexed, retrieved, and ranked video results.",
      "Later, I built data pipelines to create a steady stream of daily queries and target results that the engineering team could train on and evaluate quality against. And when we launched a small test for our first product, I created more instrumentation around results ranking and clicks to measure performance. Information like whether a person clicked on or saw a result was critical, and was fed back into our training models.",
      "We eventually launched a video module in search results, a videos tab, and a standalone video search product in the Watch tab, a new tab inside the Facebook app dedicated to videos. This work was part of the company's lockdown around videos, a top priority for the company at the time. As a result, we presented our work directly to Mark Zuckerberg, inside his all-glass meeting room called \"Aquarium\". He gave us the green light on our plan for the rest of the year.",
      { h: "What I took from those years" },
      "Across these projects and many others, my view of data science became much more product-oriented.",
      "The best data scientists I worked with were not just statisticians, SQL experts, or experiment reviewers. They were people who could build a mechanical understanding of a product.",
      "They could define what success should mean. They could identify the user behaviors that drove that success. They could find the levers that influenced those behaviors. They could quantify which levers mattered most. And they could help teams avoid wasting time on work that sounded good but was unlikely to move the system.",
      "That is still how I think about building products today.",
      "A product is a machine, but not in a cold or mechanical sense. It is a system made of people, intent, incentives, interfaces, constraints, and feedback loops. Data helps reveal how that system actually works.",
      "That is the version of data science I took from Meta: not dashboards for their own sake, not experiments as ritual, but a disciplined way to understand how products work and how to make them better. It still shapes how I build today: start with the user behavior, understand the machine, find the levers, and move the system.",
    ],
    tags: ["meta", "search", "video", "product"],
    colors: ["#1a1a26", "#7a6dd6", "#d4ccff", "#3e3a82"],
    seed: 7,
    media: "/meta-sign.jpg",
  },
];

// Secondary work — older / smaller projects, presented as a compact grid that
// opens the same ProjectModal as the reel. Ordered most-recent first.
export const ARCHIVE = [
  {
    idx: 5,
    year: "2014—2015",
    kind: "thesis · field",
    title: "Hotline Tools for Chinese Labor NGOs",
    role: "Co-author · Developer",
    blurb:
      "Masters capstone at Berkeley. After fieldwork in southern China studying labor NGOs that serve injured migrant workers, my team built TIRO — a mobile + web platform for hotline case logging, demographic reporting, and impact dashboards. Designed for low-trust, low-bandwidth environments.",
    details: [
      "For my master's thesis at Berkeley, my team built [TIRO](https://www.ischool.berkeley.edu/projects/2015/tiro), a hotline management system for small NGOs serving vulnerable communities in China.",
      "The idea came from a field research trip in China, where we studied how migrant workers adapt to city life and find safe, reliable work. During that trip, we met with several labor NGOs and saw a recurring problem: many relied on phone hotlines as a core part of their work, but still managed caller records with paper logs and manual data entry.",
      "That created two challenges. First, it made day-to-day operations inefficient. Hotline staff had no easy way to retrieve past call details, track recurring issues, or understand patterns across clients. Second, it made reporting difficult. NGOs struggled to aggregate their data into clear evidence of their work, which affected fundraising, planning, and communication with external stakeholders.",
      "This was especially important in China's political environment, where NGOs often need to demonstrate that their work is practical, constructive, and aligned with local priorities. Weak record-keeping made it harder for organizations to show their value and protect the legitimacy of their services.",
      "Our solution was to give these NGOs a simple, low-cost way to manage hotline data. We built an Android app that allowed hotline operators to log call details, record client needs, and retrieve past conversations. We also built a companion web application that helped organizations generate reports on caller demographics, relationships, services provided, and recurring issues.",
      "We partnered with an NGO in China to test the product and run a pilot. Our goal was to show that better tools could help hotline operators work more efficiently, communicate their impact more clearly, and protect sensitive client information.",
      "The project was completed in 2015. In the years since, the environment for Chinese labor NGOs has become much more difficult, with many organizations facing pressure, intimidation, and, in some cases, arrests. Because of that, our original hope — that better reporting could help strengthen relationships between labor NGOs and local governments — feels less realistic today.",
      "Still, the core idea behind TIRO remains relevant: frontline organizations need simple, secure tools to capture what they learn through direct service and turn that information into better support, better decisions, and stronger evidence of impact.",
      "TIRO was built with my Berkeley teammates [Faye Ip](https://www.linkedin.com/in/fayeip/), [Jenny Lo](https://www.linkedin.com/in/jennylo1018), and [Sophia Lay](https://www.linkedin.com/in/sophialay).",
    ],
    tags: ["berkeley", "android", "impact", "field research"],
    colors: ["#1a1812", "#a87838", "#e0c898", "#604830"],
    seed: 17,
    media: "/tiro-mobile.png",
    link: "https://www.ischool.berkeley.edu/projects/2015/tiro",
    gallery: [
      {
        type: "image",
        src: "/tiro-mobile.png",
        caption: "android app — hotline operator interface",
        figure: "Fig. 01",
      },
      {
        type: "image",
        src: "/tiro-poster3.jpg",
        caption: "project poster — berkeley capstone",
        figure: "Fig. 02",
      },
    ],
  },
  {
    idx: 6,
    year: "2013",
    kind: "ngo · volunteer",
    title: "CSIP · Hanoi",
    role: "Volunteer Developer",
    // Hidden from the Archive grid but still surfaced via the Vietnam · CSIP
    // CV row modal. Keep the full entry so getProject(6) still resolves.
    hidden: true,
    blurb:
      "Three months in Hanoi with CSIP — Vietnam's leading social-enterprise incubator, with a portfolio of ~40 ventures reaching 200K+ disadvantaged people. Rebuilt their website (information architecture, WordPress, SEO) to help them attract applicants and investment. First real exposure to founder/incubator dynamics in an emerging market.",
    details: [
      "I spent three months in Vietnam helping rebuild the website for CSIP, a Hanoi-based NGO that supports social enterprises across the country. Since 2009, CSIP has funded and advised more than 40 self-sustaining businesses, which by 2013 had improved the lives of an estimated 200,000 disadvantaged people.",
      "CSIP's work sits at the intersection of business and social impact. They train, incubate, and accelerate social startups; help NGOs become more financially sustainable; and promote the broader social enterprise movement in Vietnam through research, online resources, and public outreach.",
      "One example that stayed with me was Tòhe, one of the enterprises CSIP supported. Tòhe runs art workshops for disadvantaged children, then prints selected artwork on products like handbags, notebooks, and clothing. The children are paid for their work, giving them a way to contribute to their family's income while staying creatively engaged. It was a simple, powerful example of how a business can create both revenue and dignity.",
      "My role at CSIP was to rebuild their website. The existing site was slow, visually inconsistent, difficult to update, and unclear about what CSIP actually did. More importantly, it wasn't serving the organization's main audiences: entrepreneurs, donors, investors, partners, and NGOs.",
      "Before redesigning anything, I worked with the team to clarify what they needed the website to accomplish. We identified their key goals, ranked them by importance, and used that to shape the site's structure and content. The result was a homepage that explained CSIP's mission more clearly, highlighted its programs, and guided visitors toward meaningful actions.",
      "On the technical side, I rebuilt the site in WordPress, replacing a slower and harder-to-manage Joomla setup. I created wireframes, worked closely with a graphic designer on a cleaner visual direction, and trained CSIP's administrators to manage the new backend themselves.",
      "The new site gave CSIP a stronger platform for attracting program applicants, donors, investors, and partners. It also made the organization's work easier to understand and share, while giving the team a faster, simpler way to keep the site updated.",
      "Leaving Vietnam was harder than I expected. I came to love the country, and have returned many times since. I am still left with deep admiration for CSIP's practical, ambitious approach to social progress, and I was honored to contribute to their work.",
    ],
    tags: ["vietnam", "ngo", "social impact", "wordpress"],
    colors: ["#1a1410", "#d4604e", "#f8c8a8", "#8a3828"],
    seed: 29,
    media: "/vietnam-cover.jpg",
    gallery: [
      {
        type: "image",
        src: "/csip-team.jpg",
        caption: "with the csip team — hanoi",
        figure: "Fig. 01",
      },
      {
        type: "image",
        src: "/csip-before.jpg",
        caption: "before — the original site",
        figure: "Fig. 02",
      },
      {
        type: "image",
        src: "/csip-mockup.jpg",
        caption: "new design — mockup",
        figure: "Fig. 03",
      },
      {
        type: "image",
        src: "/csip-after.jpg",
        caption: "after — the rebuilt site",
        figure: "Fig. 04",
      },
    ],
  },
  {
    idx: 7,
    year: "2011—2012",
    kind: "nonprofit · civic",
    title: "Crowdsourcing Homeless Outreach",
    role: "Founder",
    blurb:
      "A nonprofit and Android app I founded to help homeless-relief organizations track locations of unhoused individuals in need. Piloted with Seattle's Union Gospel Mission to coordinate their Search-and-Rescue van missions. GPS-tagged needs synced to a central dispatch console.",
    details: [
      "Every night, outreach teams search city streets for people experiencing homelessness — many of whom are struggling with mental illness, addiction, injury, or exposure. The work is urgent, but often difficult to coordinate. Teams need to know where people were last seen, what kind of help they need, and whether someone has already followed up.",
      "In 2012, I built a mobile and web platform to help solve that coordination problem, then partnered with [Seattle's Union Gospel Mission](https://ugm.org/) to pilot it in the field.",
      "Seattle's Union Gospel Mission is one of the city's largest homeless outreach organizations. For nearly thirty years, its Search and Rescue team has driven through Seattle looking for people in need. Staff provide immediate help when they can — food, blankets, first aid, or transportation to shelter — and when they cannot, they mark the person's location so someone can return later.",
      "I developed an Android app that outreach staff could use during these missions. When they encountered someone in need, they could record the person's GPS location, basic situation, and requested support. For example, they could note that someone needed food and water, medical attention, a blanket, or transportation to a nearby shelter. Once submitted, the information was stored securely and made available to the broader team.",
      "I also built a web dashboard for staff at headquarters. From there, they could view reported locations, assess needs across the city, plan resources, and coordinate follow-up. Instead of relying on handwritten notes, memory, or fragmented communication, the team could work from a shared, real-time view of where help was needed most.",
      "The goal was simple: help outreach teams respond faster, coordinate better, and reduce the chance that vulnerable people were overlooked.",
      "The project ran as a year-long pilot with SUGM. After changes in internal priorities, the organization eventually stopped using the tool, and I moved on when I left for graduate school. But the experience stayed with me. It showed me how even simple technology — GPS logging, shared notes, and a common dashboard — can make frontline service work faster, more coordinated, and more humane.",
    ],
    tags: ["founder", "civic tech", "android"],
    colors: ["#181820", "#5664d8", "#c0c4ff", "#28326c"],
    seed: 19,
    media: "/srp-cover.jpg",
    gallery: [
      {
        type: "image",
        src: "/srp-11.jpg",
        caption: "the two surfaces — web + android",
        figure: "Fig. 01",
      },
      {
        type: "image",
        src: "/srp-mobile.jpg",
        caption: "logging a location — android app",
        figure: "Fig. 02",
      },
    ],
  },
  {
    idx: 8,
    year: "2009—2012",
    kind: "research · simulation",
    title: "Predicting Train Accidents",
    role: "Lead Developer",
    blurb:
      "After Graniteville and Chatsworth, congress required Class I railroads to prove ≥80% accident reduction from Positive Train Control. The FRA hired us to build the method. We invented a multi-level splitting simulator that turned 93 days of compute per study into 3. Co-published, TRR 2289 (2012).",
    details: [
      "At [DecisionTek](https://decisiontek.com/), I helped build simulation software that allowed railroads to evaluate whether Positive Train Control systems could prevent serious train accidents.",
      "The work was driven by a real safety problem. In 2005, a freight train in Graniteville, South Carolina was accidentally routed into an industrial siding, where it collided with a parked train. Several cars derailed, including chlorine tank cars; one ruptured, killing 9 people, injuring 554, and displacing thousands of nearby residents. A few years later, after another fatal collision in Chatsworth, California, Congress passed the Rail Safety Improvement Act, requiring major railroads carrying passengers or toxic inhalation materials to install Positive Train Control, or PTC.",
      "PTC systems are designed to prevent accidents by warning train crews of hazards and automatically stopping trains when necessary. But railroads also had to prove that their PTC implementations would reduce risk by at least 80%. The Federal Railroad Administration hired DecisionTek to help evaluate whether those systems delivered the required safety improvement.",
      "Our challenge was difficult: predict rare train accidents before and after PTC was installed, then compare the results.",
      "Traditional simulation was too slow for this. Even on a 12-core server, our simulator took 22 seconds to model one day of operations on a low-traffic territory. Simulating 1,000 years of operations could take 93 days — far too long for practical risk analysis.",
      "To solve this, we used a rare-event simulation technique called multi-level splitting. Instead of wasting compute on thousands of uneventful train movements, the simulator focused its resources on scenarios most likely to lead to accidents.",
      "The process worked in stages. First, the simulator generated human errors and equipment failures. When one occurred, the system paused, saved the full simulation state, stored it in the database, and continued. In the second stage, the simulator resumed from those saved error states and searched for hazardous events, such as a train exceeding its authority, overspeeding, or encountering a misaligned switch. In the final stage, it resumed from those hazardous states and simulated whether they led to collisions, derailments, or safe outcomes.",
      "This made the analysis dramatically more efficient. Rather than simulating centuries of normal operations from beginning to end, we concentrated on the branches of the simulation tree where accidents were actually plausible.",
      "The software then used the results from each stage to estimate how often different accident types would occur. We ran the analysis twice: once for the base case without PTC, and once for the alternate case with PTC. Comparing the two allowed railroads to demonstrate whether their PTC systems achieved the required 80% risk reduction.",
      "The result was a simulator that could produce statistically reliable PTC risk analyses in as little as three days. Our work was [later published in Transportation Research Record](https://journals.sagepub.com/doi/abs/10.3141/2289-05), giving railroads a practical way to validate their safety systems and giving the FRA a stronger basis for approving technologies designed to make rail operations safer.",
    ],
    tags: ["decisiontek", "fra", "simulation", "published"],
    colors: ["#162018", "#4a8a64", "#cce4d4", "#2a5840"],
    seed: 11,
    media: "/bnsf.webp",
    gallery: [
      {
        type: "image",
        src: "/staged-simulation1.png",
        caption: "multi-level splitting — three-stage simulation",
        figure: "Fig. 01",
      },
      {
        type: "image",
        src: "/simulation-results.png",
        caption: "simulation results — base case vs ptc",
        figure: "Fig. 02",
      },
    ],
  },
  {
    idx: 9,
    year: "2009—2012",
    kind: "tool · data viz",
    title: "Modeling Railroads",
    role: "Lead Developer",
    blurb:
      "A visual editor for the railroad-infrastructure data feeding the simulator. 12 spreadsheets per territory became a single interactive canvas; a graph-traversal algorithm validated connectivity in real time. 3 weeks of analyst work became 3 days. Built solo over four months in Silverlight + .NET.",
    details: [
      "At [DecisionTek](https://decisiontek.com/), I built a visual railroad infrastructure editor that reduced a process that once took weeks of spreadsheet work into a few days of interactive modeling.",
      "DecisionTek's train movement simulator helped rail operators evaluate the safety of their territories. To produce accurate simulations, the software needed detailed infrastructure data: track length, connectivity, grades, curves, [switches](https://en.wikipedia.org/wiki/Railroad_switch), crossings, signals, and speed limits. Previously, users had to define all of this across 12 spreadsheets, which was slow, error-prone, and difficult for non-technical users.",
      "Our goal was to replace that spreadsheet-heavy workflow with a visual interface. Instead of manually editing rows of infrastructure data, users could see a simplified track diagram, click on segments, edit properties, add new track, and immediately validate whether the territory made sense.",
      "I built the software over four months using Microsoft Silverlight and the .NET Framework.",
      "The core challenge was visualizing the track network accurately. Railroad territories are essentially graphs: track segments connect to other segments or to switches, and switches allow lines to split or merge. One of the most common user errors was incorrect connectivity — for example, saying one segment connected to the wrong next segment. To catch these problems, I used a graph traversal algorithm to construct the visualization directly from the underlying data. If the data was wrong, the diagram would expose the issue.",
      "The algorithm searched through every combination of system entry point, exit point, and direction, then positioned each infrastructure element on the canvas based on its relationship to the rest of the network. Track length determined horizontal position, while vertical position came from the user-defined layout. I also had to handle more complex topology, including [sidings](https://en.wikipedia.org/wiki/Siding_(rail)), [crossovers](https://en.wikipedia.org/wiki/Railroad_switch#Crossover), and [wyes](https://en.wikipedia.org/wiki/Wye_(rail)), where the simplified diagram needed to remain readable while still respecting the real structure of the track.",
      "Beyond the track itself, the tool visualized grades, curves, and speed zones. This helped users spot problems like impossible elevation changes, overly sharp curves, or incorrect speed restrictions. Users could also click any segment to inspect or edit its underlying data.",
      "Once the visualization worked, I added editing tools: context menus, forms, editable grids, database updates, spreadsheet uploads, and the ability to create entirely new rail systems from scratch. Users could start with a blank canvas, add entry points, build track through a series of clicks, and connect parallel lines with crossovers.",
      "The result was a much faster and more intuitive workflow. Modeling a 100-mile double-track territory could take as little as three days, compared with roughly three weeks using the previous spreadsheet-based process. Troubleshooting requests dropped substantially, and railroad customers praised both the accuracy of the diagrams and the smoother simulation workflow.",
    ],
    tags: ["silverlight", ".NET", "graph", "data viz"],
    colors: ["#201912", "#c89844", "#ffe0b0", "#806440"],
    seed: 13,
    media: "/tracktool.jpg",
    gallery: [
      {
        type: "image",
        src: "/tracktool.jpg",
        caption: "main canvas view",
        figure: "Fig. 01",
      },
      {
        type: "image",
        src: "/tt-sg-trackchart2.jpg",
        caption:
          "Track chart example ([Michael Froio](https://michaelfroio.wordpress.com/category/architecture-2/page/2/))",
        figure: "Fig. 02",
      },
      {
        type: "image",
        src: "/tt-track-network.png",
        caption: "track network — graph traversal",
        figure: "Fig. 03",
      },
      {
        type: "image",
        src: "/tt-data-model.jpg",
        caption: "underlying data model",
        figure: "Fig. 04",
      },
      {
        type: "image",
        src: "/tt-context-menu.jpg",
        caption: "in-canvas context menu",
        figure: "Fig. 05",
      },
      {
        type: "image",
        src: "/tt-create-new-segment.jpg",
        caption: "creating a new segment",
        figure: "Fig. 06",
      },
      {
        type: "image",
        src: "/tt-edit-grades.jpg",
        caption: "editing grades, curves, speed zones",
        figure: "Fig. 07",
      },
    ],
  },
];

export const EXPERIENCE = [
  {
    dates: "2024—NOW",
    org: "bello.art",
    role: "Founder · CEO",
    bullets: [
      "Founded bello.art, a visual commerce platform helping artists create premium product imagery, starting with high-end wall art mockups and a browser-based mockup editor.",
      "Sold 10,000+ mockups to independent artists and creative sellers; earned 1,000+ reviews with a 5-star average and Etsy Star Seller status.",
      "Built a memory-efficient WebGL/Next.js alternative to Photoshop that lets artists insert, resize, frame, and export artwork in advanced PSD-based mockups without Photoshop.",
      "Shipped a companion Photoshop plugin with 6,000+ downloads, later featured by Adobe Photoshop on Instagram.",
      "Launched bello.art in 2026 as a direct ecommerce channel, expanding beyond Etsy into premium mockup packs, saved artist workflows, and AI-generated scene imagery.",
    ],
    projects: [1],
  },
  {
    dates: "2022—2024",
    org: "Adobe",
    role: "Photoshop Partner · Sponsored Creator",
    bullets: [
      "Official Adobe Photoshop partner and sponsored creator, producing original artwork, tutorials, and short-form content for Photoshop's global creative community.",
      "Created 23 short-form videos and 3 original artworks for Adobe campaigns, generating 60M views and 1M likes across Instagram and TikTok.",
    ],
    projects: [2],
  },
  {
    dates: "2020—2021",
    org: "Meta",
    role: "Data Science Manager, Reality Labs — AR Experiences",
    bullets: [
      "Led data science for the AR Experiences pillar within Meta Reality Labs, managing 5 data scientists and partnering with a ~100-person product/engineering org building mobile AR experiences foundational to Meta's AR glasses strategy.",
      "Identified major friction in the AR creator ecosystem and shaped the case for a dedicated 3D content platform, helping secure new headcount and driving a 40× increase in AR content inventory.",
      "Led data strategy across Commerce, World Experiences, Location Experiences, and Remote Presence, overseeing 90+ experiments and translating results into product roadmaps, OKRs, and leadership strategy docs.",
      "Identified consumer opportunities for bringing 3D objects into Instagram Feed, leading to a cross-org collaboration across Camera, 3D Scanning, and Instagram platform teams.",
    ],
    projects: [3],
  },
  {
    dates: "2015—2020",
    org: "Meta",
    role: "Data Scientist",
    bullets: [
      "Drove product strategy and experimentation across Facebook Lite, Messenger, Search, Business Platform, and Reality Labs, partnering with PM, engineering, design, and research to ship 100+ product improvements.",
      "Identified 10+ usability issues in Facebook Pages, a product used by 1B+ monthly users, and drove experiments that increased key business actions, including +2% Page likes and +5% website clicks.",
      "Discovered that Facebook was undercounting Pages visits by 30%, convinced leadership to launch a logging overhaul, and revealed a +1% increase in active businesses, a topline company metric.",
      "Led analysis of Facebook Search failure patterns and partnered with engineers to improve keyword suggestions and ranking, reducing failed searches by 5M and increasing search result click rate by 2%.",
      "Helped build and launch Facebook's first video search engine, from sizing user demand and identifying query opportunities to aligning Search and Video teams; presented the work to Mark Zuckerberg before launch.",
    ],
    projects: [4],
  },
  {
    dates: "2013—2015",
    org: "UC Berkeley",
    role: "Master in Information Management and Systems (MIMS)",
    bullets: [
      "Awarded 1st Prize, James R. Chen Award for best master's final project.",
      "Built [TIRO](https://www.ischool.berkeley.edu/projects/2015/tiro), a hotline management system for labor NGOs in China; also placed 2nd in the [Berkeley Big Ideas ICT for Society challenge](https://citris-uc.org/big-ideas-2015-winners-bcapi-takes-first-place/).",
      "Conducted field research in southern China with labor NGOs supporting injured migrant workers and vulnerable urban communities.",
    ],
    projects: [5],
  },
  {
    dates: "2013",
    org: "Vietnam · CSIP",
    role: "Volunteer Developer",
    bullets: [
      "Three months in Hanoi with CSIP — Vietnam's leading social-enterprise incubator (~40 ventures reaching 200K+ disadvantaged people).",
      "Rebuilt their website (information architecture, WordPress, SEO) to attract applicants and investment.",
      "First real exposure to founder/incubator dynamics in an emerging market.",
    ],
    projects: [6],
  },
  {
    dates: "2009—2012",
    org: "DecisionTek",
    role: "Product Manager & Software Engineer",
    bullets: [
      "Helped develop GTMS, a train movement simulation platform funded by the Federal Railroad Administration to estimate rare freight-train accident risk and evaluate Positive Train Control safety performance.",
      "Built an interactive Silverlight/.NET infrastructure editor that transformed spreadsheet-based rail territory modeling into a visual workflow, reducing data-entry time by ~80%.",
      "Co-published the project's [rare-event simulation methodology](https://journals.sagepub.com/doi/abs/10.3141/2289-05) in Transportation Research Record, the leading U.S. transportation research journal.",
    ],
    projects: [8, 9],
  },
];
